# Generated by Django 4.2.7 on 2023-12-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('description', models.CharField(max_length=250, verbose_name='Опис товару')),
                ('price', models.FloatField(verbose_name='Ціна')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('date', models.DateTimeField(verbose_name='Дата публікації')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
