# Generated by Django 4.2.7 on 2024-01-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.CharField(max_length=250, verbose_name='Адреса доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Прізвище'),
        ),
    ]
