# Generated by Django 4.2.7 on 2024-02-09 17:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_order_options_alter_order_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='myapp.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Номер телефону повинен бути валідним.', regex='^\\+38?\\d{10}$')]),
        ),
    ]
